<a href="https://colab.research.google.com/github/diegoflxgarcia/Pandas/blob/main/pandas04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Criando colunas

In [32]:
import pandas as pd

Importando novamente o arquivo dataset [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv), usado no arquivo pandas01.ipynb e pandas03.ipynb

In [33]:
# Importando novamente os dados
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
dados = pd.read_csv(url)
display(dados)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

## Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles.

Vamos criar uma coluna que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles.

In [34]:
dados = dados.assign(Pontos_extras = dados['Notas']*0.4)
display(dados)

         Nome  Idade  Notas  Aprovado  Pontos_extras
0         Ary     20    7.5      True           3.00
1         Ana     18    NaN     False            NaN
2       Cátia     27    2.5     False           1.00
3       Denis     18    5.0     False           2.00
4        Beto     21   10.0      True           4.00
5       Bruna     23    NaN     False            NaN
6        Dara     21    7.0      True           2.80
7      Carlos     19    6.0      True           2.40
8       Alice     35    5.6     False           2.24
9       Vitor     28    NaN     False            NaN
10     Daniel     21    NaN     False            NaN
11       Igor     24    4.5     False           1.80
12  Sthefanie     26    9.5      True           3.80
13      Mirla     25    9.0      True           3.60
14      Paulo     37    NaN     False            NaN
15     Mylena     29    7.0      True           2.80
16      Lucas     33    NaN     False            NaN
17      Nadia     34    8.0      True           3.20

## Vamos criar mais uma coluna, que possua as notas de cada aluno somada com os pontos extras.

In [35]:
dados['Notas_finais'] = dados['Notas'] + dados['Pontos_extras']

# Ajustandos as notas maiores que 10, o ideal é a nota máxima ser 10...
dados['Notas_finais'] = dados['Notas_finais'].apply(lambda nota: 10 if nota > 10 else nota)

display(dados)

         Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais
0         Ary     20    7.5      True           3.00         10.00
1         Ana     18    NaN     False            NaN           NaN
2       Cátia     27    2.5     False           1.00          3.50
3       Denis     18    5.0     False           2.00          7.00
4        Beto     21   10.0      True           4.00         10.00
5       Bruna     23    NaN     False            NaN           NaN
6        Dara     21    7.0      True           2.80          9.80
7      Carlos     19    6.0      True           2.40          8.40
8       Alice     35    5.6     False           2.24          7.84
9       Vitor     28    NaN     False            NaN           NaN
10     Daniel     21    NaN     False            NaN           NaN
11       Igor     24    4.5     False           1.80          6.30
12  Sthefanie     26    9.5      True           3.80         10.00
13      Mirla     25    9.0      True           3.60         10.00
14      Paulo     37    NaN     False            NaN           NaN
15     Mylena     29    7.0      True           2.80          9.80
16      Lucas     33    NaN     False            NaN           NaN
17      Nadia     34    8.0      True           3.20         10.00

## Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Portanto, vamos criar uma coluna com os seguintes valores:

- True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
- False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

In [36]:
dados['Aprovado_final'] = dados['Notas_finais'].apply(lambda nota: True if nota >= 6 else False)
display(dados)

,Nome,Idade,Notas,Aprovado,Pontos_extras,Notas_finais,Aprovado_final
0,Ary,20,7.5,True,3.00,10.00,True
1,Ana,18,NaN,False,NaN,NaN,False
2,Cátia,27,2.5,False,1.00,3.50,False
3,Denis,18,5.0,False,2.00,7.00,True
4,Beto,21,10.0,True,4.00,10.00,True
5,Bruna,23,NaN,False,NaN,NaN,False
6,Dara,21,7.0,True,2.80,9.80,True
7,Carlos,19,6.0,True,2.40,8.40,True
8,Alice,35,5.6,False,2.24,7.84,True
9,Vitor,28,NaN,False,NaN,NaN,False
10,Daniel,21,NaN,False,NaN,NaN,False
11,Igor,24,4.5,False,1.80,6.30,True
12,Sthefanie,26,9.5,True,3.80,10.00,True
13,Mirla,25,9.0,True,3.60,10.00,True
14,Paulo,37,NaN,False,NaN,NaN,False
15,Mylena,29,7.0,True,2.80,9.80,True
16,Lucas,33,NaN,False,NaN,NaN,False
17,Nadia,34,8.0,True,3.20,10.00,True

## Fazendo uma seleção e verificando quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras.

In [42]:
# Poderiamos usar o método query também...
aprovados_posteriormente = (dados['Aprovado'] == False) & (dados['Aprovado_final'] == True)
selecao_aprovados_posteriormente = dados[aprovados_posteriormente]

display(selecao_aprovados_posteriormente)

     Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais  Aprovado_final
3   Denis     18    5.0     False           2.00          7.00            True
8   Alice     35    5.6     False           2.24          7.84            True
11   Igor     24    4.5     False           1.80          6.30            True