<a href="https://colab.research.google.com/github/diegoflxgarcia/Pandas/blob/main/pandas03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tratando, filtrando, alterando e salvando alterações em uma base de dados

In [112]:
import pandas as pd

Importando novamente o arquivo dataset [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv), usado no arquivo pandas01.ipynb

In [113]:
# Importando novamente os dados
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
dados = pd.read_csv(url)
display(dados)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

## Verificando se a base de dados possui dados nulos e caso tenha, vamos realizar o tratamento desses dados nulos

In [114]:
# Tem dados nulos?
display(dados.isnull().sum())

Nome        0
Idade       0
Notas       6
Aprovado    0
dtype: int64

In [115]:
# Provavelmente os alunos sem nota tiraram 0, então basta preencher com 0 essas notas...
dados.fillna(0, inplace=True)
display(dados['Notas'])

0      7.5
1      0.0
2      2.5
3      5.0
4     10.0
5      0.0
6      7.0
7      6.0
8      5.6
9      0.0
10     0.0
11     4.5
12     9.5
13     9.0
14     0.0
15     7.0
16     0.0
17     8.0
Name: Notas, dtype: float64

## Os alunos "Alice" e "Carlos" não fazem mais parte da turma e portanto vamos remove-los

In [116]:
# Consultando as linhas (índices) dos alunos em questão...
alunos_a_remover = dados.query('Nome == "Alice" | Nome == "Carlos"').index
display(alunos_a_remover)

Int64Index([7, 8], dtype='int64')

In [117]:
# Removendo e confirmando a remoção
dados.drop(alunos_a_remover, inplace=True)
display(dados['Nome'])

0           Ary
1           Ana
2         Cátia
3         Denis
4          Beto
5         Bruna
6          Dara
9         Vitor
10       Daniel
11         Igor
12    Sthefanie
13        Mirla
14        Paulo
15       Mylena
16        Lucas
17        Nadia
Name: Nome, dtype: object

## Filtrando apenas os alunos que foram aprovados

In [118]:
aprovados = dados['Aprovado'] == True

In [119]:
alunos_aprovados = dados[aprovados]
display(alunos_aprovados)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    7.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    7.0      True
17      Nadia     34    8.0      True

## Salvando o DataFrame "alunos_aprovados" em um arquivo csv chamado "alunos_aprovados.csv"

In [120]:
alunos_aprovados.to_csv('alunos_aprovados.csv', index=False)

In [121]:
# Verificando se foi salvo corretamente
display(pd.read_csv('alunos_aprovados.csv'))

        Nome  Idade  Notas  Aprovado
0        Ary     20    7.5      True
1       Beto     21   10.0      True
2       Dara     21    7.0      True
3  Sthefanie     26    9.5      True
4      Mirla     25    9.0      True
5     Mylena     29    7.0      True
6      Nadia     34    8.0      True

## Ao conferir as notas dos alunos aprovados, notamos que algumas notas estavam incorretas. Os alunos que tiraram nota 7.0, na verdade tinham um ponto extra que não foi contabilizado. Sendo assim, vamos substituir as notas 7.0 da base de dados por 8.0

In [122]:
# Para ser aprovado é necessário ter nota maior ou igual a 6, sendo assim podemos alterar direto no dataframe anteriror
alunos_aprovados.replace(7.0, 8.0, inplace=True)
alunos_aprovados.to_csv('alunos_aprovados_corrigido.csv', index=False)
display(alunos_aprovados)

<ipython-input-122-6d97260f5f98>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alunos_aprovados.replace(7.0, 8.0, inplace=True)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    8.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    8.0      True
17      Nadia     34    8.0      True